version: "3.9"

networks:
  default:
    name: lookum

services:
  db:
    image: frenzy/db:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  api:
    depends_on:
      - db
    image: frenzy/api:latest
    networks:
      default:
        aliases:
          - "api-server"
    volumes:
      - server-data:/lookum/data

  proxy:
    depends_on:
      - api
    image: frenzy/proxy:latest
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - "proxy"  
    volumes:
      - server-data:/var/www

volumes:
  pgdata:
    external: true
  server-data:
    external: true